### ISSUE TITLE
Missing menu voices text (ITALIAN translation) [ver 1.3]

### ISSUE THREAD

**Issue by PhilRoll** [Rinnegatamante/re3#2]
I had a problem using italian translation.
if i select italian language, some menu voices have no text (showing for exemple "fet gra missing" or similar). i had a clean install (steam folder, decoded audio, insert data package, and installed 1.3 vpk).

**Comment by Rinnegatamante** [comment]
If you have v.1.3 data files, this is a re3 issue, not a vita port one.
