### ISSUE TITLE
[GTA3], car bug driving over dead pedestrians

### ISSUE THREAD

**Issue by daveh077** [Rinnegatamante/re3#5]
When you try to drive over dead pedestrians or their dropped money the car acts like they are solid objects, you crash into them and can't move. 

E.g I managed to flip the car just by trying to drive over a dead body.

**Comment by Rinnegatamante** [comment]
Never had such an issue with money.

**Comment by daveh077** [comment]
Yea it's very strange, I tried it again with the latest version tonight and it's still present, apparently it wasn't present in version 1.1

**Comment by Griffathan** [comment]
> When you try to drive over dead pedestrians or their dropped money the car acts like they are solid objects, you crash into them and can't move.
> 
> E.g I managed to flip the car just by trying to drive over a dead body.

I have the exact same issue

**Comment by J013k** [comment]
I have almost the same problem with ver v1.3.

It happens about a second after they are dead on the ground,
they act as a solid object.
I cannot drive or walk through them.

**Comment by J013k** [comment]
This bug should be fixed in ver v.1.4:
https://vitadb.rinnegatamante.it/#/info/589.
